version: '3.8'

networks:
  shared_net:
    external: true
  private_net:
    driver: bridge

services:
  simplex-smp:
    image: simplexchat/smp-server:latest
    container_name: simplex-smp
    platform: linux/amd64
    restart: always
    environment:
      - SMP_SERVER_STORE_LOG=on
      - ADDR=10.0.2.2
    ports:
      - "5223:5223"
    volumes:
      - ./smp_data:/opt/simplex/smp
      - ./smp-server.ini:/opt/simplex/smp/smp-server.ini
      - ./certificates:/certificates:ro
    networks:
      - shared_net
      - private_net
    healthcheck:
      test: ["CMD-SHELL", "timeout 1 bash -c '</dev/tcp/localhost/5223' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  simplex-xftp:
    image: simplexchat/xftp-server:latest
    container_name: simplex-xftp
    platform: linux/amd64
    restart: always
    environment:
      - XFTP_SERVER_STORE_LOG=on
      - ADDR=10.0.2.2
      - QUOTA=1gb
      - PASS=
    ports:
      - "5443:5443"
    volumes:
      - ./xftp_data:/opt/simplex/xftp
      - ./xftp-server.ini:/opt/simplex/xftp/xftp-server.ini
      - ./certificates:/certificates:ro
    networks:
      - shared_net
      - private_net
    healthcheck:
      test: ["CMD-SHELL", "timeout 1 bash -c '</dev/tcp/localhost/443' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# volumes:
  # smp_data:
  # xftp_data:
