services:
  proxy:
    image: mitmproxy/mitmproxy:10.4.2
    container_name: newpipe_proxy
    command: mitmdump --listen-port 8082 --set block_global=false
    env_file: [.env]
    volumes:
      - proxy_data:/home/mitmproxy/.mitmproxy
      - ./flows:/flows
    ports:
      - "${PROXY_PORT}:8082"

volumes:
  proxy_data: 