services:
  orchestrator:
    build:
      context: .
      dockerfile: Dockerfile.dind
    container_name: mobilecybench-orchestrator
    privileged: true
    volumes:
      - .:/app
      - docker-data:/var/lib/docker
      - gradle-cache:/root/.gradle
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      # Uncomment these 2 lines (ANDROID_ADB_SERVER_ADDRESS, ANDROID_ADB_SERVER_PORT) if using host-side ADB server (not needed for in-container emulator)
      - ANDROID_ADB_SERVER_ADDRESS=host.docker.internal
      - ANDROID_ADB_SERVER_PORT=5037
      - DOCKER_TLS_CERTDIR=
    command: ["tail", "-f", "/dev/null"]

volumes:
  docker-data:
  gradle-cache:
