services:
    backend:
      build:
        context: .
        dockerfile: Dockerfile.backend
      container_name: mobilecybench-backend
      privileged: true
      tty: true
      stdin_open: true
      volumes:
        - dind-data:/var/lib/docker
        - ./:/mobilecybench
        - /var/run/docker.sock:/var/run/docker.sock
        - $HOME/.ssh:/root/.ssh
        - gradle-cache:/root/.gradle
        - android-sdk:/root/.android-sdk
      environment:
        - OPENAI_API_KEY=${OPENAI_API_KEY:-}
        - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY:-}
        - GRADLE_USER_HOME=/root/.gradle
        - ANDROID_SDK_ROOT=/root/.android-sdk
        - GRADLE_OPTS=-Xmx6g -Dfile.encoding=UTF-8
        - JAVA_TOOL_OPTIONS=-Xmx6g
      networks:
        - app-network
      extra_hosts:
        - "host.docker.internal:host-gateway"

networks:
  shared_net:
    driver: bridge
  app-network:
      driver: bridge

volumes:
  dind-data:
    external: true
  gradle-cache:
  android-sdk:
