[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mobilecybench"
version = "0.0.1"

[tool.setuptools.packages.find]
include = ["utils"]

[tool.pytest.ini_options]
markers = [
    "pricing: mark tests related to token pricing",
    "token_tracker: mark tests related to token tracker",
]

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = ["E501"]  # let Black handle line length

