# version: '3'

services:
  vaultwarden:
    image: vaultwarden/server:1.34.3
    restart: always
    ports:
      - "8080:80"
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
    volumes:
      - ./vw-data:/data
    depends_on:
      - db
    networks:
      - shared_net
      - private_net

  db:
    image: postgres:14.9
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes: 
      - db_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - private_net

volumes:
  db_data:

networks:
  shared_net:
    # external: true
  private_net: 