import os
import uuid
import json
import hashlib
import hmac
from base64 import b64encode

# pycryptodome is required: pip install pycryptodome
from Crypto.Cipher import AES
from Crypto.Util.Padding import pad
from Crypto.Random import get_random_bytes
from Crypto.PublicKey import RSA

# import hashlib
# import binascii

# password = "MasterPassword1"
# salt = bytes.fromhex("b3ff4cb3a72fdfe5db3edc901b2f1f61fb19ae28ca3a20431b040d15f04828db10142d4529475039b0aeeb0df6fca9c389dd579d56737b56f604e192fefc2f23")
# iterations = 600000
# hash = hashlib.pbkdf2_hmac('sha256', password.encode('utf-8'), salt, iterations, dklen=32)
# print("Hash bytes:", hash)
# print("Hash hex:", hash.hex())

def verify_hash(password, salt, expected_hash_hex, iterations):
    """
    Verifies that the hash generated by Python matches the expected hash from Vaultwarden.
    """
    import binascii
    actual_hash = hashlib.pbkdf2_hmac('sha256', password.encode('utf-8'), salt, iterations, dklen=32)
    actual_hash_hex = actual_hash.hex()
    print(f"[VERIFY] Password: {password}")
    print(f"[VERIFY] Salt (hex): {salt.hex()}")
    print(f"[VERIFY] Hash (hex): {actual_hash_hex}")
    print(f"[VERIFY] Expected Hash (hex): {expected_hash_hex}")
    if actual_hash_hex == expected_hash_hex:
        print("[VERIFY] ✅ Hash matches expected value!")
    else:
        print("[VERIFY] ❌ Hash does NOT match expected value!")

# Fill in the actual password for this user!
password = "MasterPassword5"
salt = bytes.fromhex("0e5900b53e7b65462a7c699b65ea3b97e7982a9c34df21ed1f33b415ba8b60e0c83b61e3404db347fe5fa7f6e469c2d4d945209aa6b006c83c8e17d9346c32e4")
expected_hash_hex = "fa6157421628919cfb3761e7ade2491b5d9fba3584055bee0708f51a40d0ab7f"
iterations = 600000

verify_hash(password, salt, expected_hash_hex, iterations)

import hashlib
import unicodedata

def make_stretched_key(password, email, iterations):
    # Normalize email as Vaultwarden might
    normalized_email = unicodedata.normalize('NFC', email.lower().strip())
    return hashlib.pbkdf2_hmac('sha256', password.encode('utf-8'), normalized_email.encode('utf-8'), iterations, dklen=32)

def hash_password_direct(master_key, salt, iterations):
    return hashlib.pbkdf2_hmac('sha256', master_key, salt, iterations, dklen=32)

# Fill in the actual values:
password = "MasterPassword5"
email = "user5@example.com"
client_kdf_iter = 600000
server_iterations = 600000
salt = bytes.fromhex("704f886f527483cce3591bd510c57dafe3d3cda9cf55f7d5eee9ee13eb4245feb401e0cb340c811cce7fa53703b5a33854f46b3a9320dfa4938a8d0cde77b91f")
expected_hash_hex = "2a6362a77ca3845c47e8fbf793418724298fee5f3ce32a19d72381183ab4b440"

# Debug prints
print("Password repr:", repr(password))
print("Email repr:", repr(email))
normalized_email = unicodedata.normalize('NFC', email.lower().strip())
print("Normalized email:", repr(normalized_email))
print("Salt (hex):", salt.hex())
print("client_kdf_iter:", client_kdf_iter)
print("server_iterations:", server_iterations)

# Step 1: Client-side KDF
master_key = make_stretched_key(password, email, client_kdf_iter)
# Step 2: Server-side KDF
password_hash = hash_password_direct(master_key, salt, server_iterations)

print("Master key (hex):", master_key.hex())
print("Computed hash (hex):", password_hash.hex())
print("Expected hash (hex):", expected_hash_hex)
print("Match:", password_hash.hex() == expected_hash_hex)