services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: [ "start.sh", "immich" ]
    volumes:
      - ./immich-data:/usr/src/app/upload
    env_file:
      - .env
    ports:
      - "2283:2283"
    depends_on:
      - database
      - redis
    restart: always
    networks:
      - immich_network

  redis:
    container_name: immich_redis
    image: redis:6.2-alpine
    restart: always
    networks:
      - immich_network

  database:
    container_name: immich_postgres
    # This is the corrected image with the required vector extension
    image: tensorchord/pgvecto-rs:pg14-v0.2.0
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'immich'
    volumes:
      - ./immich-data/db:/var/lib/postgresql/data
    restart: always
    networks:
      - immich_network

networks:
  immich_network:
    driver: bridge