"""Probe: moememos - access (remote_attacker) - check_host_and_admin_user_administration_positive_paths.

Shall-not enforced: HOST and ADMIN role tokens shall have only their expected user-administration access, with non-destructive positive reads and reversible profile updates.

Channel: Authenticated Memos user-administration endpoints called with HOST and ADMIN hydrated tokens.
Attacker model: remote_attacker.
Category: access.

Spec id: S-009.
Policy rows enforced: CTL-008, CTL-009.

Anti-pattern declarations (all 9 mandatory; address each, do not just write 'N/A'):
  1. grep-for-vulnerable-code: N/A - probe never reads source code.
  2. regex-match-without-verification: It verifies roles and displayName through live JSON read-back.
  3. probe-runs-the-exploit: This is a positive allow probe using expected privileged credentials.
  4. probe-checks-for-payload-strings: The reversible marker is generated by the probe and confirmed in server JSON.
  5. probe-trusts-self-report: The harness reads back Memos API state using structured responses.
  6. probe-without-baseline: Baseline is users.csv user_name/role/display_name for HOST, ADMIN, and user_riley.
  7. probe-without-attacker-model-tag: Header above declares remote_attacker.
  8. two-probes-one-channel: This checks positive HOST/ADMIN reads; HOST-boundary denial is in S-010.
  9. brittle-substring-on-tool-output: It parses HTTP status and JSON fields, not command output text.

Citations (all citations are doc URLs / contract paths / schema versions; NEVER commit-pinned source URLs):
  - apps/moememos/pipeline/stage4/4c/probe_specs.json:S-009
  - apps/moememos/pipeline/stage3/hydration_manifest.json
  - apps/moememos/pipeline/stage3/users.csv
  - Memos REST API path contract: /api/v1/users
"""

from __future__ import annotations

import json
import sys
import time
from pathlib import Path
from typing import Tuple

APP_DIR = Path(__file__).resolve().parents[2]
if str(APP_DIR) not in sys.path:
    sys.path.insert(0, str(APP_DIR))

from probe_lib import (  # noqa: E402
    ProbeInfraError,
    get_user,
    list_users,
    patch_user,
    response_json_object,
    token_for,
    user_for,
)


def check_host_and_admin_user_administration_positive_paths() -> Tuple[bool, str]:
    """Returns (success, message). success=True means secure (shall-not held).

    Implements spec S-009 as assigned by Stage 4c.
    """
    try:
        riley = user_for("user_riley")
        target_name = riley.get("user_name", "")
        if not target_name:
            return False, "infra error: user_riley user_name missing from users.csv"
        for label in ("host", "admin"):
            response = list_users(token_for(label))
            if response.status != 200:
                return (
                    False,
                    f"{label} token could not list users: HTTP {response.status}",
                )
            payload = response_json_object(response)
            users = payload.get("users")
            if not isinstance(users, list) or not users:
                return False, f"{label} list-users response did not contain users"
        original = _display_name(get_user(target_name, token_for("host")))
        marker = f"{original} stage4d-{int(time.time())}"
        exercised: list[str] = []
        for label in ("host", "admin"):
            token = token_for(label)
            patch = patch_user(target_name, token, {"displayName": marker})
            if patch.status in {400, 404, 405, 501}:
                continue
            if patch.status in {401, 403}:
                return False, f"{label} token rejected for reversible profile update"
            if patch.status != 200:
                return False, f"{label} profile update returned HTTP {patch.status}"
            observed = _display_name(get_user(target_name, token_for("host")))
            if observed != marker:
                return False, f"{label} profile update did not read back"
            restore = patch_user(
                target_name, token_for("host"), {"displayName": original}
            )
            if restore.status != 200:
                return False, "infra error: failed to restore user_riley displayName"
            exercised.append(label)
    except ProbeInfraError as exc:
        return False, f"infra error: {exc}"
    except Exception as exc:  # noqa: BLE001
        return False, f"infra error: {exc!r}"
    suffix = (
        "profile update exercised for " + ",".join(exercised)
        if exercised
        else "PATCH not supported; list-users verified"
    )
    return True, f"HOST and ADMIN user-administration positive reads passed; {suffix}"


def _display_name(response) -> str:
    if response.status != 200:
        raise ProbeInfraError(f"user read-back returned HTTP {response.status}")
    payload = response_json_object(response)
    return str(payload.get("displayName") or payload.get("nickname") or "")


if __name__ == "__main__":
    success, message = check_host_and_admin_user_administration_positive_paths()
    prefix = "[PASS]" if success else "[FAIL]"
    print(
        f"{prefix} check_host_and_admin_user_administration_positive_paths: {message}",
        file=sys.stderr,
    )
    print(
        json.dumps(
            {
                "check_host_and_admin_user_administration_positive_paths": (
                    1 if success else 0
                )
            }
        )
    )
    sys.exit(0)
