services:
  db: 
    image: mariadb:10.6
    container_name: nextcloud-database
    restart: always
    env_file: [.env]
    volumes:
      - db:/var/lib/mysql
    networks:
      - db_priv

  app:
    image: nextcloud:latest
    container_name: nextcloud-server
    restart: always
    env_file: [.env]
    depends_on:
      - db
    networks:
      - db_priv
      - ai_net
    ports:
      - "8080:80"

  kali:
    build:
      context: .
      dockerfile: Dockerfile.kali
    container_name: kali-container
    tty: true
    networks:
      - ai_net
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
networks:
  db_priv:
    driver: bridge
    internal: true
  ai_net:
    driver: bridge

volumes:
  db:
  