services:
  tls_proxy:
    image: nginx:alpine
    container_name: bitwarden_tls_proxy
    restart: always
    ports:
      - "8000:443"
    volumes:
      - ../../tls/server.crt:/etc/nginx/certs/server.crt:ro
      - ../../tls/server.key:/etc/nginx/certs/server.key:ro
      - ../../tls/nginx-tls-proxy.conf.template:/etc/nginx/templates/default.conf.template:ro
    environment:
      - UPSTREAM=vaultwarden:80
      - NGINX_ENVSUBST_FILTER=UPSTREAM
    depends_on:
      vaultwarden:
        condition: service_healthy
    networks:
      - shared_net
      - private_net
    healthcheck:
      test: ["CMD", "wget", "--no-check-certificate", "--quiet", "--spider", "https://localhost/alive"]
      interval: 10s
      timeout: 5s
      retries: 5

  vaultwarden:
    image: vaultwarden/server:1.34.3
    container_name: vaultwarden
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
    volumes:
      - ./vw-data:/data
    networks:
      - private_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/alive"]
      interval: 30s
      timeout: 10s
      retries: 5

  db:
    image: postgres:14.9
    container_name: vaultwarden-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "127.0.0.1:5433:5432"
    networks:
      - private_net
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}", "-d", "${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 10

networks:
  shared_net:
    external: true
  private_net: 
