FROM python:3.12-alpine@sha256:6d43704baacd1bfbe7c295d7f13079d5d8104ed33568873133f8fc69980419df

WORKDIR /opt/hydration
COPY receiver.py /opt/hydration/receiver.py

CMD ["python", "/opt/hydration/receiver.py"]
