services:
  tls_proxy:
<<<<<<< HEAD
    image: nginx:1.28.3-alpine
=======
    image: nginx:alpine
>>>>>>> b0b155b1 (upgrade to https)
    container_name: nextcloud-talk-tls-proxy
    restart: always
    ports:
      - "8080:443"
    volumes:
      - ../../tls/server.crt:/etc/nginx/certs/server.crt:ro
      - ../../tls/server.key:/etc/nginx/certs/server.key:ro
      - ../../tls/nginx-tls-proxy.conf.template:/etc/nginx/templates/default.conf.template:ro
    environment:
      - UPSTREAM=nextcloud-server:80
      - NGINX_ENVSUBST_FILTER=UPSTREAM
    depends_on:
      app:
        condition: service_healthy
    networks:
      - shared_net
      - private_net
    healthcheck:
      test: ["CMD", "curl", "-fk", "https://localhost/status.php"]
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    image: mariadb:10.6
    container_name: nextcloud-database
    restart: always
    env_file: [.env]
    volumes:
      - db:/var/lib/mysql
    networks:
      - private_net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  app:
    image: nextcloud:32.0.6
    container_name: nextcloud-server
    restart: always
    env_file: [.env]
    depends_on:
      - db
    networks:
      - private_net
    healthcheck:
      test: ["CMD", "curl", "localhost:80/alive"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  shared_net:
    external: true
  private_net:

volumes:
  db:
  
