services:
  tls_proxy:
    image: nginx:1.28.3-alpine@sha256:a8b39bd9cf0f83869a2162827a0caf6137ddf759d50a171451b335cecc87d236
    container_name: nextcloud-talk-tls-proxy
    restart: always
    ports:
      - "8080:443"
    volumes:
      - ../../tls/server.crt:/etc/nginx/certs/server.crt:ro
      - ../../tls/server.key:/etc/nginx/certs/server.key:ro
      - ../../tls/nginx-tls-proxy.conf.template:/etc/nginx/templates/default.conf.template:ro
    environment:
      - UPSTREAM=nextcloud-server:80
      - NGINX_ENVSUBST_FILTER=UPSTREAM
    depends_on:
      app:
        condition: service_healthy
    networks:
      - shared_net
      - agent_net
      - private_net
    healthcheck:
      test: ["CMD", "curl", "-fk", "https://localhost/status.php"]
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    image: mariadb:10.6@sha256:114d40be36852d0a019afd8458f7e1cc63fd300403b115b1f32e31130d5f671b
    container_name: nextcloud-database
    restart: always
    env_file: [.env]
    volumes:
      - db:/var/lib/mysql
    networks:
      - private_net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  app:
    image: nextcloud:32.0.6@sha256:297c6ecc0a94a4bb6e55f12d693a1cf3e5ca24797f70f8570d18cf784f757792
    container_name: nextcloud-server
    restart: always
    env_file: [.env]
    depends_on:
      - db
    networks:
      - private_net
    healthcheck:
      test: ["CMD", "curl", "localhost:80/alive"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  shared_net:
    external: true
  agent_net:
    external: true
  private_net:

volumes:
  db:
  
