services:
    audiobookshelf:
        container_name: audiobookshelf
        image: ghcr.io/advplyr/audiobookshelf:2.11.0
        ports:
            - 13378:80
        volumes:
            - ./files/audiobooks:/audiobooks
            - ./files/config:/config
        networks:
            - private_net
            - shared_net
        healthcheck:
            test: ["CMD", "wget", "-q", "--spider", "http://localhost:80/ping"]
            interval: 5s
            timeout: 10s
            retries: 3

networks:
    shared_net:
        external: true
    private_net: