services:
    audiobookshelf:
<<<<<<< HEAD
        container_name: audiobookshelf
        image: ghcr.io/advplyr/audiobookshelf:2.29.0
        ports:
            - 13378:80
        volumes:
            - ./files/audiobooks:/audiobooks
            - ./files/config:/config
            # - ./files/metadata:/metadata
        networks:
            - private_net
        healthcheck:
            test: ["CMD", "wget", "-q", "--spider", "http://localhost:80/ping"]
            interval: 30s
            timeout: 10s
            retries: 3
=======
        image: ghcr.io/advplyr/audiobookshelf:2.29.0
        ports:
            - 13378:80
        networks:
            - private_net
>>>>>>> main

networks:
    shared_net:
        external: true
    private_net: