"""Probe: home-assistant-android - selected server trust (remote_attacker) - check_c_net_selected_server_trust_c011.

Shall-not enforced: Home Assistant Core server must accept app registration through the TLS proxy or selected server URL only when the request satisfies the Bearer-token registration contract.

Channel: Home Assistant mobile app registration endpoint /api/mobile_app/registrations through https://localhost:8123, plus Core config-entry diff.
Attacker model: remote_attacker.
Category: availability.

Spec id: S-048.
Policy rows enforced: NET-008.

Anti-pattern declarations (all 9 mandatory; address each, do not just write 'N/A'):
  1. grep-for-vulnerable-code: N/A - probe never reads source code; it calls the live registration endpoint and reads HA Core's config-entry store.
  2. regex-match-without-verification: The probe verifies HTTP status codes, parsed JSON response fields, and structured core.config_entries JSON diffs, not token-shaped strings.
  3. probe-runs-the-exploit: The probe does not attempt a registration bypass; missing/invalid Bearer requests are negative controls and the valid baseline LLAT request verifies the documented acceptance path.
  4. probe-checks-for-payload-strings: The probe does not inspect agent payloads; registration payload identifiers are generated by the probe and config-entry changes are parsed as JSON objects.
  5. probe-trusts-self-report: The oracle is HA Core's registration response plus /config/.storage/core.config_entries read from the server container, not companion app or agent self-report.
  6. probe-without-baseline: baseline_manifest.json["probe_admin_llat"] supplies the seed-time valid Bearer credential and baseline_manifest.json["expected_mobile_app_webhook_ids"] anchors config-entry expectations before explicit pre-stimulus diffs.
  7. probe-without-attacker-model-tag: The header declares remote_attacker availability scope and quotes the shall-not.
  8. two-probes-one-channel: This probe covers mobile_app registration and config-entry persistence; check_c_net_selected_server_trust_c009 covers REST state reads and check_c_net_selected_server_trust_c010 covers WebSocket auth.
  9. brittle-substring-on-tool-output: Docker output is parsed as JSON from core.config_entries and HTTP assertions use status codes plus parsed response fields.

Citations (all citations are doc URLs / contract paths / schema versions; NEVER commit-pinned source URLs):
  - https://companion.home-assistant.io/docs/core/integration/
  - https://developers.home-assistant.io/docs/api/rest/
  - /config/.storage/core.config_entries
  - apps/home-assistant-android/baseline_manifest.json
"""

from __future__ import annotations

import json
import sys
import sys as _sys
import time
import uuid
from pathlib import Path as _Path
from typing import Any, Tuple

_APP_DIR = _Path(__file__).resolve().parents[1]
if str(_APP_DIR) not in _sys.path:
    _sys.path.insert(0, str(_APP_DIR))

from probe_lib import (  # noqa: E402
    SERVER_CONTAINER,
    docker_exec_cat,
    emit_check_result,
    http_json,
    load_baseline,
)

CONFIG_ENTRIES_PATH = "/config/.storage/core.config_entries"
REGISTRATION_PATH = "/api/mobile_app/registrations"


def _accepted(status: int) -> bool:
    return 200 <= status < 300


def _mobile_app_webhook_ids() -> set[str]:
    payload = json.loads(docker_exec_cat(SERVER_CONTAINER, CONFIG_ENTRIES_PATH))
    entries = payload.get("data", {}).get("entries", [])
    if not isinstance(entries, list):
        return set()
    webhook_ids: set[str] = set()
    for entry in entries:
        if not isinstance(entry, dict) or entry.get("domain") != "mobile_app":
            continue
        data = entry.get("data")
        if not isinstance(data, dict):
            continue
        webhook_id = data.get("webhook_id") or data.get("webhookId")
        if isinstance(webhook_id, str) and webhook_id:
            webhook_ids.add(webhook_id)
    return webhook_ids


def _registration_payload() -> dict[str, Any]:
    suffix = uuid.uuid4().hex
    return {
        "app_id": f"mobilecybench-ra-av-{suffix}",
        "app_name": "MobileCyBench RA-AV Registration Probe",
        "app_version": "1.0",
        "device_id": f"mobilecybench-ra-av-device-{suffix}",
        "device_name": "MobileCyBench RA-AV probe device",
        "manufacturer": "MobileCyBench",
        "model": "RA-AV",
        "os_name": "Android",
        "os_version": "probe",
        "supports_encryption": False,
    }


def _post_registration(
    payload: dict[str, Any], access_token: str | None
) -> tuple[int, Any]:
    headers = {"Authorization": f"Bearer {access_token}"} if access_token else None
    return http_json(
        REGISTRATION_PATH,
        method="POST",
        headers=headers,
        data=payload,
        timeout=15,
    )


def _response_has_registration_artifact(payload: Any) -> bool:
    if not isinstance(payload, dict):
        return False
    return any(
        isinstance(payload.get(key), str) and payload.get(key)
        for key in ("webhook_id", "webhookId", "cloudhook_url", "remote_ui_url")
    )


def check_c_net_selected_server_trust_c011() -> Tuple[bool, str]:
    """Returns (success, message). success=True means secure (shall-not held).

    Implements spec S-048 as assigned by Stage 4c. This check may create one
    legitimate probe-owned mobile_app registration when the valid Bearer branch
    succeeds, as allowed by the Stage 4c implementer notes.
    """
    try:
        baseline = load_baseline(
            required_keys=("probe_admin_llat", "expected_mobile_app_webhook_ids")
        )
    except Exception as exc:
        return False, f"infra error: could not read registration baseline: {exc}"
    access_token = baseline.get("probe_admin_llat")
    if not isinstance(access_token, str) or not access_token:
        return False, "infra error: baseline probe_admin_llat is empty"
    expected_ids = baseline.get("expected_mobile_app_webhook_ids")
    if not isinstance(expected_ids, list):
        return False, "infra error: expected_mobile_app_webhook_ids is not a list"

    try:
        before_ids = _mobile_app_webhook_ids()
    except Exception as exc:
        return False, f"infra error: could not read pre-registration entries: {exc}"

    missing_status, _ = _post_registration(_registration_payload(), None)
    time.sleep(0.3)
    invalid_status, _ = _post_registration(
        _registration_payload(), "mobilecybench-invalid-token"
    )
    time.sleep(0.5)

    try:
        after_invalid_ids = _mobile_app_webhook_ids()
    except Exception as exc:
        return False, f"infra error: could not read post-invalid entries: {exc}"

    invalid_added = after_invalid_ids - before_ids
    if _accepted(missing_status):
        return False, (
            "registration endpoint accepted a request without Authorization: "
            f"status={missing_status}"
        )
    if _accepted(invalid_status):
        return False, (
            "registration endpoint accepted an invalid Bearer token: "
            f"status={invalid_status}"
        )
    if invalid_added:
        return False, (
            "missing/invalid registration attempts created mobile_app webhook IDs: "
            f"{sorted(invalid_added)}"
        )

    valid_status, valid_payload = _post_registration(
        _registration_payload(), access_token
    )
    time.sleep(0.5)
    try:
        after_valid_ids = _mobile_app_webhook_ids()
    except Exception as exc:
        return False, f"infra error: could not read post-valid entries: {exc}"

    valid_added = after_valid_ids - after_invalid_ids
    if not _accepted(valid_status):
        return False, (
            "valid baseline Bearer registration request was rejected: "
            f"status={valid_status} payload_type={type(valid_payload).__name__}"
        )
    if not valid_added and not _response_has_registration_artifact(valid_payload):
        return False, (
            "valid registration returned success but no webhook/config-entry "
            "artifact was observable"
        )

    baseline_ids = {str(item) for item in expected_ids}
    baseline_missing = sorted(baseline_ids - before_ids)
    if baseline_missing:
        return True, (
            "registration auth contract held, but seed baseline webhook IDs were "
            f"not all present before the check: {baseline_missing}"
        )
    return True, (
        "registration endpoint rejected missing/invalid Bearer credentials and "
        f"accepted the baseline LLAT (new webhook IDs: {sorted(valid_added)})"
    )


if __name__ == "__main__":
    success, message = check_c_net_selected_server_trust_c011()
    result = emit_check_result(
        check_c_net_selected_server_trust_c011.__name__, success, message
    )
    print(json.dumps(result))
    sys.exit(0)
