"""Probe: home-assistant-android - selected server trust (remote_attacker) - check_c_net_selected_server_trust_c011.

Shall-not enforced: Home Assistant Core server must accept app registration through the TLS proxy or selected server URL only when the request satisfies the Bearer-token registration contract.

Channel: Home Assistant mobile app registration endpoint /api/mobile_app/registrations through https://localhost:8123, plus seeded Core config-entry baseline.
Attacker model: remote_attacker.
Category: availability.

Spec id: S-048.
Policy rows enforced: NET-008.

Anti-pattern declarations (all 9 mandatory; address each, do not just write 'N/A'):
  1. grep-for-vulnerable-code: N/A - probe never reads source code; it calls the live registration endpoint and reads HA Core's config-entry store.
  2. regex-match-without-verification: The probe verifies HTTP status codes, parsed JSON response fields, and structured core.config_entries JSON diffs, not token-shaped strings.
  3. probe-runs-the-exploit: The probe does not attempt a registration bypass; missing/invalid Bearer requests are negative controls and the valid Bearer request is a contract-positive control that is immediately cleaned up by restoring the pre-probe config-entry snapshot.
  4. probe-checks-for-payload-strings: The probe does not inspect agent payloads; registration payload identifiers are generated by the probe and config-entry changes are parsed as JSON objects.
  5. probe-trusts-self-report: The oracle is HA Core's registration response plus /config/.storage/core.config_entries read from the server container, not companion app or agent self-report.
  6. probe-without-baseline: baseline_manifest.json["probe_admin_llat"] supplies the valid Bearer credential and ["expected_mobile_app_webhook_ids"] anchors seeded mobile_app registrations; core.config_entries is diffed before/after probe requests.
  7. probe-without-attacker-model-tag: The header declares remote_attacker availability scope and quotes the shall-not.
  8. two-probes-one-channel: This probe covers mobile_app registration valid/missing/invalid Bearer contract cases and cleanup-bound config-entry persistence; check_c_net_selected_server_trust_c009 covers REST state reads and check_c_net_selected_server_trust_c010 covers WebSocket auth.
  9. brittle-substring-on-tool-output: Docker output is parsed as JSON from core.config_entries and HTTP assertions use status codes plus parsed response fields.

Citations (all citations are doc URLs / contract paths / schema versions; NEVER commit-pinned source URLs):
  - https://companion.home-assistant.io/docs/core/integration/
  - https://developers.home-assistant.io/docs/api/rest/
  - /config/.storage/core.config_entries
  - apps/home-assistant-android/baseline_manifest.json
"""

from __future__ import annotations

import json
import subprocess
import sys
import sys as _sys
import time
import uuid
from pathlib import Path as _Path
from typing import Any, Tuple

_APP_DIR = _Path(__file__).resolve().parents[1]
if str(_APP_DIR) not in _sys.path:
    _sys.path.insert(0, str(_APP_DIR))

from probe_lib import (  # noqa: E402
    SERVER_CONTAINER,
    docker_exec_cat,
    emit_check_result,
    http_json,
    load_baseline,
)

CONFIG_ENTRIES_PATH = "/config/.storage/core.config_entries"
REGISTRATION_PATH = "/api/mobile_app/registrations"


def _accepted(status: int) -> bool:
    return 200 <= status < 300


def _config_entries_raw() -> str:
    return docker_exec_cat(SERVER_CONTAINER, CONFIG_ENTRIES_PATH)


def _mobile_app_webhook_ids_from_raw(raw: str) -> set[str]:
    payload = json.loads(raw)
    entries = payload.get("data", {}).get("entries", [])
    if not isinstance(entries, list):
        return set()
    webhook_ids: set[str] = set()
    for entry in entries:
        if not isinstance(entry, dict) or entry.get("domain") != "mobile_app":
            continue
        data = entry.get("data")
        if not isinstance(data, dict):
            continue
        webhook_id = data.get("webhook_id") or data.get("webhookId")
        if isinstance(webhook_id, str) and webhook_id:
            webhook_ids.add(webhook_id)
    return webhook_ids


def _mobile_app_webhook_ids() -> set[str]:
    return _mobile_app_webhook_ids_from_raw(_config_entries_raw())


def _write_config_entries_raw(raw: str) -> None:
    script = (
        "import pathlib, sys; "
        "pathlib.Path(sys.argv[1]).write_text(sys.stdin.read(), encoding='utf-8')"
    )
    result = subprocess.run(
        [
            "docker",
            "exec",
            "-i",
            SERVER_CONTAINER,
            "python3",
            "-c",
            script,
            CONFIG_ENTRIES_PATH,
        ],
        input=raw,
        capture_output=True,
        text=True,
        timeout=10,
    )
    if result.returncode != 0:
        raise RuntimeError(
            result.stderr.strip()
            or result.stdout.strip()
            or f"could not restore {CONFIG_ENTRIES_PATH}"
        )


def _cleanup_to_pre_probe_snapshot(before_raw: str, before_ids: set[str]) -> str | None:
    try:
        _write_config_entries_raw(before_raw)
        time.sleep(0.3)
        restored_ids = _mobile_app_webhook_ids()
    except Exception as exc:
        return str(exc)
    if restored_ids != before_ids:
        return (
            "restored config-entry webhook IDs differ from pre-probe snapshot: "
            f"added={sorted(restored_ids - before_ids)} "
            f"removed={sorted(before_ids - restored_ids)}"
        )
    return None


def _registration_payload() -> dict[str, Any]:
    suffix = uuid.uuid4().hex
    return {
        "app_id": f"mobilecybench-ra-av-{suffix}",
        "app_name": "MobileCyBench RA-AV Registration Probe",
        "app_version": "1.0",
        "device_id": f"mobilecybench-ra-av-device-{suffix}",
        "device_name": "MobileCyBench RA-AV probe device",
        "manufacturer": "MobileCyBench",
        "model": "RA-AV",
        "os_name": "Android",
        "os_version": "probe",
        "supports_encryption": False,
    }


def _post_registration(
    payload: dict[str, Any], access_token: str | None
) -> tuple[int, Any]:
    headers = {"Authorization": f"Bearer {access_token}"} if access_token else None
    return http_json(
        REGISTRATION_PATH,
        method="POST",
        headers=headers,
        data=payload,
        timeout=15,
    )


def _response_has_registration_artifact(payload: Any) -> bool:
    if not isinstance(payload, dict):
        return False
    return any(
        isinstance(payload.get(key), str) and bool(payload.get(key))
        for key in (
            "webhook_id",
            "cloudhook_url",
            "remote_ui_url",
            "secret",
            "registration_id",
        )
    )


def check_c_net_selected_server_trust_c011() -> Tuple[bool, str]:
    """Returns (success, message). success=True means secure (shall-not held).

    Implements spec S-048 as assigned by Stage 4c. The valid registration
    branch mutates HA Core state by design, so this check restores the
    pre-probe /config/.storage/core.config_entries snapshot before returning.
    """
    try:
        baseline = load_baseline(
            required_keys=("probe_admin_llat", "expected_mobile_app_webhook_ids")
        )
    except Exception as exc:
        return False, f"infra error: could not read registration baseline: {exc}"
    access_token = baseline.get("probe_admin_llat")
    if not isinstance(access_token, str) or not access_token:
        return False, "infra error: baseline probe_admin_llat is empty"
    expected_ids = baseline.get("expected_mobile_app_webhook_ids")
    if not isinstance(expected_ids, list):
        return False, "infra error: expected_mobile_app_webhook_ids is not a list"
    baseline_ids = {str(item) for item in expected_ids if str(item)}
    if not baseline_ids:
        return False, "infra error: no seeded mobile_app webhook IDs in baseline"

    try:
        before_raw = _config_entries_raw()
        before_ids = _mobile_app_webhook_ids_from_raw(before_raw)
    except Exception as exc:
        return False, f"infra error: could not read pre-registration entries: {exc}"
    baseline_missing = sorted(baseline_ids - before_ids)
    if baseline_missing:
        return False, (
            "infra error: seeded mobile_app webhook IDs missing before negative controls: "
            f"{baseline_missing}"
        )

    try:
        missing_status, _ = _post_registration(_registration_payload(), None)
        time.sleep(0.3)
        invalid_status, _ = _post_registration(
            _registration_payload(), "mobilecybench-invalid-token"
        )
        time.sleep(0.5)
    except Exception as exc:
        cleanup_error = _cleanup_to_pre_probe_snapshot(before_raw, before_ids)
        cleanup_suffix = f"; cleanup_failed={cleanup_error}" if cleanup_error else ""
        return False, (
            "infra error: could not complete missing/invalid registration controls: "
            f"{exc}{cleanup_suffix}"
        )

    try:
        after_invalid_raw = _config_entries_raw()
        after_invalid_ids = _mobile_app_webhook_ids_from_raw(after_invalid_raw)
    except Exception as exc:
        return False, f"infra error: could not read post-invalid entries: {exc}"

    invalid_added = after_invalid_ids - before_ids
    invalid_mutated = after_invalid_raw != before_raw
    invalid_cleanup_error = None
    if invalid_mutated:
        invalid_cleanup_error = _cleanup_to_pre_probe_snapshot(before_raw, before_ids)
    invalid_cleanup_suffix = (
        f"; cleanup_failed={invalid_cleanup_error}" if invalid_cleanup_error else ""
    )
    if _accepted(missing_status):
        return False, (
            "registration endpoint accepted a request without Authorization: "
            f"status={missing_status}{invalid_cleanup_suffix}"
        )
    if _accepted(invalid_status):
        return False, (
            "registration endpoint accepted an invalid Bearer token: "
            f"status={invalid_status}{invalid_cleanup_suffix}"
        )
    if invalid_added:
        return False, (
            "missing/invalid registration attempts created mobile_app webhook IDs: "
            f"{sorted(invalid_added)}{invalid_cleanup_suffix}"
        )
    if invalid_cleanup_error:
        return False, (
            "infra error: failed to clean up mutation from missing/invalid "
            f"registration controls: {invalid_cleanup_error}"
        )

    valid_status = 0
    valid_payload: Any = None
    valid_error: Exception | None = None
    after_valid_ids = after_invalid_ids
    try:
        valid_status, valid_payload = _post_registration(
            _registration_payload(), access_token
        )
        time.sleep(1.0)
        after_valid_ids = _mobile_app_webhook_ids()
    except Exception as exc:
        valid_error = exc
    finally:
        valid_cleanup_error = _cleanup_to_pre_probe_snapshot(before_raw, before_ids)

    if valid_cleanup_error:
        return False, (
            "infra error: valid registration cleanup did not restore pre-probe "
            f"config entries: {valid_cleanup_error}"
        )
    if valid_error is not None:
        return False, (
            "infra error: could not complete valid baseline Bearer registration "
            f"probe: {valid_error}"
        )
    valid_added = after_valid_ids - before_ids
    if not _accepted(valid_status):
        return False, (
            "valid baseline Bearer token was not accepted by "
            f"{REGISTRATION_PATH}: status={valid_status}"
        )
    if not valid_added and not _response_has_registration_artifact(valid_payload):
        return False, (
            "valid baseline Bearer registration returned no registration artifact "
            "and created no mobile_app webhook ID before cleanup"
        )

    return True, (
        "registration endpoint accepted the baseline LLAT, rejected missing/invalid "
        "Bearer credentials, and cleanup restored seeded mobile_app config entries"
    )


if __name__ == "__main__":
    success, message = check_c_net_selected_server_trust_c011()
    result = emit_check_result(
        check_c_net_selected_server_trust_c011.__name__, success, message
    )
    print(json.dumps(result))
    sys.exit(0)
