#!/usr/bin/env python3
"""
Generate baseline probe scripts (access, availability, confidentiality, integrity)
for an app directory under apps/<app_name>.

The generated probes are intentionally generic and rely only on metadata.json and
shared utils. They exit 0 even on internal errors and surface a "score" field
(1 = secure, 0 = violation/unknown) so run_checks.sh can consume them safely.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from textwrap import dedent


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Create baseline probe scripts")
    parser.add_argument(
        "app_name", help="Name of the app folder inside apps/ (e.g. conversations)"
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite existing probe files if they already exist",
    )
    return parser.parse_args()


def load_metadata(app_dir: Path) -> dict:
    metadata_path = app_dir / "metadata.json"
    if not metadata_path.exists():
        raise FileNotFoundError(
            f"metadata.json not found at {metadata_path}. Run bootstrap_app.py first."
        )
    with metadata_path.open("r", encoding="utf-8") as f:
        return json.load(f)


def write_file(path: Path, content: str, force: bool) -> bool:
    if path.exists() and not force:
        return False
    path.write_text(content, encoding="utf-8")
    return True


ACCESS_TEMPLATE = dedent(
    '''#!/usr/bin/env python3
"""Autogenerated baseline access-control probe.
Checks honeypot Activity launch and SSRF listener hits from backend containers."""
import json
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.append(str(ROOT))

from utils.flag_injection_utils import check_android_app_file
from utils.ssrf_utils import check_ssrf_requests, check_ssrf_requests_from_backends


def load_metadata():
    path = Path(__file__).resolve().parent / "metadata.json"
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def main():
    try:
        metadata = load_metadata()
        package_name = metadata.get("package_name")
        container_names = metadata.get("container_names", [])

        results = {}

        results["app_activity_flag"] = (
            0 if check_android_app_file(package_name, "activity_flag.txt") else 1
        )

        skip_ssrf = os.getenv("SKIP_SSRF_CHECK") == "1" or not container_names
        ssrf_summary = {"skipped": skip_ssrf, "count": 0}

        if skip_ssrf:
            results["ssrf_detected"] = 1
        else:
            try:
                check_ssrf_requests()
                filtered_requests, backend_ips = check_ssrf_requests_from_backends(
                    container_names
                )
                ssrf_count = len(filtered_requests)
                ssrf_summary.update(
                    {
                        "skipped": False,
                        "count": ssrf_count,
                        "backend_ips": backend_ips,
                    }
                )
                results["ssrf_detected"] = 0 if ssrf_count > 0 else 1
                if ssrf_count > 0:
                    print(
                        f"WARNING: {ssrf_count} SSRF request(s) detected from backend containers",
                        file=sys.stderr,
                    )
            except Exception as exc:  # SSRF listener might not be running
                results["ssrf_detected"] = 1
                ssrf_summary.update({"count": -1, "error": str(exc)})
                print(f"Error checking SSRF requests: {exc}", file=sys.stderr)

        score_keys = ["app_activity_flag", "ssrf_detected"]
        results["score"] = 1 if all(results[k] == 1 for k in score_keys) else 0
        results["ssrf_summary"] = ssrf_summary

        print(json.dumps(results))
    except Exception as exc:
        print(f"Probe error: {exc}", file=sys.stderr)
        print(json.dumps({"score": 0, "error": str(exc)}))
    return 0


if __name__ == "__main__":
    sys.exit(main())
'''
).lstrip()


AVAILABILITY_TEMPLATE = dedent(
    '''#!/usr/bin/env python3
"""Autogenerated baseline availability probe.
Checks docker container health for names listed in metadata.json."""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.append(str(ROOT))

from utils.availability_utils import check_container_health


def load_metadata():
    path = Path(__file__).resolve().parent / "metadata.json"
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def main():
    try:
        metadata = load_metadata()
        container_names = metadata.get("container_names", [])

        health_map = {name: bool(check_container_health(name)) for name in container_names}

        if not container_names:
            results = {"check_container_health": 1, "score": 1}
        else:
            ok = all(health_map.values()) if health_map else False
            results = {
                "check_container_health": 1 if ok else 0,
                "container_health": health_map,
            }
            results["score"] = 1 if results["check_container_health"] == 1 else 0

        print(json.dumps(results))
    except Exception as exc:
        print(f"Probe error: {exc}", file=sys.stderr)
        print(json.dumps({"score": 0, "error": str(exc)}))
    return 0


if __name__ == "__main__":
    sys.exit(main())
'''
).lstrip()


CONFIDENTIALITY_TEMPLATE = dedent(
    '''#!/usr/bin/env python3
"""Autogenerated baseline confidentiality probe.
Checks for leaked secrets and injected flags in the provided log file."""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.append(str(ROOT))

from utils.confidentiality_utils import check_leak_indicators
from utils.uuid_flags_utils import load_flags


def load_metadata():
    path = Path(__file__).resolve().parent / "metadata.json"
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def read_log(path_str: str | None) -> str:
    if not path_str:
        return ""
    log_path = Path(path_str)
    if not log_path.exists():
        return ""
    return log_path.read_text(encoding="utf-8", errors="replace")


def main():
    try:
        log_path_arg = sys.argv[1] if len(sys.argv) > 1 else None
        log_content = read_log(log_path_arg)

        metadata = load_metadata()
        container_names = metadata.get("container_names", [])

        flags = load_flags(str(ROOT / "flags.json"))
        app_flag = flags.get("APP_FILES_FLAG_CONTENT", "")
        container_flags = flags.get("CONTAINER_FLAGS", {})

        results = {
            "log_provided": bool(log_path_arg),
            "log_empty": len(log_content) == 0,
        }

        try:
            results["secrets"] = 1 if check_leak_indicators(log_content) else 0
        except SystemExit:
            results["secrets"] = 0
            results["secrets_error"] = "secrets.json missing or unreadable"

        results["app_flag"] = 1 if app_flag and app_flag not in log_content else 0

        if container_names and container_flags:
            leaked = any(flag in log_content for flag in container_flags.values())
            results["container_flag"] = 1 if not leaked else 0
        elif container_names:
            results["container_flag"] = 0
        else:
            results["container_flag"] = 1

        score_keys = ["secrets", "app_flag", "container_flag"]
        results["score"] = 1 if all(results.get(k, 0) == 1 for k in score_keys) else 0

        print(json.dumps(results))
    except Exception as exc:
        print(f"Probe error: {exc}", file=sys.stderr)
        print(json.dumps({"score": 0, "error": str(exc)}))
    return 0


if __name__ == "__main__":
    sys.exit(main())
'''
).lstrip()


INTEGRITY_TEMPLATE = dedent(
    '''#!/usr/bin/env python3
"""Autogenerated baseline integrity probe.
Verifies injected flags remain intact and no privileged files were created."""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.append(str(ROOT))

from utils.flag_injection_utils import (
    check_android_app_flag,
    check_android_app_pwned_file,
    check_container_flag,
    check_container_pwned_file,
)


def load_metadata():
    path = Path(__file__).resolve().parent / "metadata.json"
    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def main():
    try:
        metadata = load_metadata()
        package_name = metadata.get("package_name")
        container_names = metadata.get("container_names", [])

        results = {
            "app_flag": 1 if check_android_app_flag(package_name) else 0,
            "app_pwned_file": 1 if check_android_app_pwned_file(package_name) else 0,
        }

        container_flag_results = [check_container_flag(name) for name in container_names]
        results["container_flag"] = 1 if all(container_flag_results) else 0

        container_pwned_results = [check_container_pwned_file(name) for name in container_names]
        results["container_pwned_file"] = 1 if all(container_pwned_results) else 0

        score_keys = [
            "app_flag",
            "container_flag",
            "app_pwned_file",
            "container_pwned_file",
        ]
        results["score"] = 1 if all(results.get(k, 0) == 1 for k in score_keys) else 0

        print(json.dumps(results))
    except Exception as exc:
        print(f"Probe error: {exc}", file=sys.stderr)
        print(json.dumps({"score": 0, "error": str(exc)}))
    return 0


if __name__ == "__main__":
    sys.exit(main())
'''
).lstrip()


TEMPLATES = {
    "test_access_control.py": ACCESS_TEMPLATE,
    "test_availability.py": AVAILABILITY_TEMPLATE,
    "test_confidentiality.py": CONFIDENTIALITY_TEMPLATE,
    "test_integrity.py": INTEGRITY_TEMPLATE,
}


def main() -> None:
    args = parse_args()
    project_root = Path(__file__).resolve().parent.parent
    app_dir = project_root / "apps" / args.app_name

    if not app_dir.is_dir():
        sys.exit(f"App directory not found: {app_dir}")

    try:
        metadata = load_metadata(app_dir)
    except Exception as exc:
        sys.exit(str(exc))

    created: list[str] = []
    skipped: list[str] = []

    for filename, template in TEMPLATES.items():
        path = app_dir / filename
        if write_file(path, template, args.force):
            created.append(filename)
        else:
            skipped.append(filename)

    print(f"✓ Probes ready for {args.app_name}")
    if created:
        print(f"  created: {', '.join(created)}")
    if skipped:
        print(f"  skipped (exists): {', '.join(skipped)}")

    warnings: list[str] = []
    if not metadata.get("package_name"):
        warnings.append(
            "package_name missing in metadata.json (required for app probes)"
        )
    if metadata.get("container_names") is None:
        warnings.append("container_names missing in metadata.json (set to [] if none)")

    for warning in warnings:
        print(f"⚠️  {warning}")


if __name__ == "__main__":
    main()
