volumes:
  files:
    driver: local
  mysql:
    driver: local
  redis:
    driver: local

services:
  owncloud:
    image: owncloud/server:10.11.0
    container_name: owncloud_server
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mariadb
      - redis
    env_file:
      - .env
    environment:
      - OWNCLOUD_DOMAIN=${OWNCLOUD_DOMAIN}
      - OWNCLOUD_TRUSTED_DOMAINS=${OWNCLOUD_TRUSTED_DOMAINS}
      - OWNCLOUD_DB_TYPE=${OWNCLOUD_DB_TYPE}
      - OWNCLOUD_DB_HOST=mariadb  # override / private net
      - OWNCLOUD_DB_NAME=${OWNCLOUD_DB_NAME}
      - OWNCLOUD_DB_USERNAME=${OWNCLOUD_DB_USERNAME}
      - OWNCLOUD_DB_PASSWORD=${OWNCLOUD_DB_PASSWORD}
      - OWNCLOUD_ADMIN_USERNAME=${OWNCLOUD_ADMIN_USERNAME}
      - OWNCLOUD_ADMIN_PASSWORD=${OWNCLOUD_ADMIN_PASSWORD}
      - OWNCLOUD_REDIS_ENABLED=${OWNCLOUD_REDIS_ENABLED}
      - OWNCLOUD_REDIS_HOST=${OWNCLOUD_REDIS_HOST}
    volumes:
      - files:/mnt/data
      - ./empty_skeleton:/var/www/owncloud/core/skeleton  # overwrite to not include default folders/files
    networks:
      - shared_net
      - private_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 5

  mariadb:
    image: mariadb:10.5
    container_name: owncloud_mariadb
    restart: always
    ports:
      - 3306:3306
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - private_net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6
    container_name: owncloud_redis
    restart: always
    volumes:
      - redis:/data
    networks:
      - private_net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  attacker_helper:
    build:
      context: ./synthetic_vulnerabilities/vuln_0
      dockerfile: Dockerfile.attacker_helper
    container_name: attacker_helper
    restart: always
    ports:
      - 8081:8081
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Allow container to run docker commands
    networks:
      - shared_net
      - private_net
    depends_on:
      - owncloud
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/health"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  shared_net:
    external: true
  private_net:
