services:
  memos-server:
    image: neosmemo/memos:0.22.5
    container_name: memos-server
    restart: always
    ports:
      - 5230:5230
    volumes:
      - memos-data:/var/opt/memos
    networks:
      - shared_net
    healthcheck:
      test: ["NONE"]

volumes:
  memos-data:
    driver: local

networks:
  shared_net:
    external: true
