# Reference configuration for a simple Tinode server.
# Includes:
# * Mysql database
# * Tinode server

services:
  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    # Use your own volume.
    # volumes:
    #   - <mysql directory in your file system>:/var/lib/mysql
    command: >
      bash -c "
      docker-entrypoint.sh mysqld &
      sleep 5 &&
      mysql -u root -p${MYSQL_ROOT_PASSWORD} -e \"DROP DATABASE IF EXISTS ${MYSQL_DATABASE}; GRANT CREATE ON *.* TO '${MYSQL_USER}'@'%'; FLUSH PRIVILEGES;\" &&
      wait
      "
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u${MYSQL_USER}", "-p${MYSQL_PASSWORD}"]
      timeout: 5s
      retries: 10
    networks:
      - private_net
  
  tinode-server:
    image: tinode/tinode-mysql:0.23
    platform: linux/amd64
    container_name: tinode-server
    hostname: tinode-server
    depends_on:
      db:
        condition: service_healthy
    restart: always
    # You can mount your volumes as necessary:
    # volumes:
      # Mount the data.json file so Tinode can load sample data
      # - ./data.json:/opt/tinode/data.json
      # E.g. external config (assuming EXT_CONFIG is set).
      # - <path to your tinode.conf>:/etc/tinode/tinode.conf
      # Logs directory.
      # - <path to your tinode-0 logs directory>:/var/log
    ports:
      - "6060:6060"
    environment:
      MYSQL_DSN: ${TINODE_MYSQL_DSN}
      RESET_DB: true
      WAIT_FOR: db:3306
      SAMPLE_DATA: ""
    networks:
      - private_net
      - shared_net

networks:
  private_net:
    driver: bridge
    internal: true
  shared_net:
    # external: true
  